#version: "3.9"
services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  receiver:
    build:
      context: ./receiver
      dockerfile: Dockerfile
    restart: on-failure
    container_name: receiver
    depends_on:
      - rabbit
    volumes:
      - maven_repo:/root/.m2
  sender:
    build:
      context: ./sender
      dockerfile: Dockerfile
    restart: on-failure
    container_name: sender
    depends_on:
      - rabbit
    ports:
      - "8080:8080"
    volumes:
      - maven_repo:/root/.m2
volumes:
  maven_repo:
    external: true